# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:53
from __future__ import unicode_literals

import apps.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[apps.login.models.valid_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, validators=[apps.login.models.valid_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, validators=[apps.login.models.valid_name]),
        ),
    ]
