# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.User'),
        ),
    ]
