# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eedb97e3f8949704b4252347cae4b15d80a0916d1f0dc22564f09949bbc8b9cb637d0afb3f42aadaebeecf96d91d4487dd60a4cad1d36eb621943ef2f52b1af

test:
  secret_key_base: adb48e07e39fd69468b5b57460e1a405a6fa849cceb94a9abf3cf4f0d14a03abf2a8a695c4f0209721c68526026651b46f94ee476ef3ded32b5542c5d811b06c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
